name: Back-end build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build server project
        run: dotnet publish --project ReactTSCSharpStarter -c Release -o /app --no-restore
      - name: Run tests
        run: dotnet test --no-restore
